### ISSUE TITLE
Comparative Examination of GEM-Sreen and GEM

### ISSUE THREAD

**Issue by daydayupzzl** [jinfeng-data/GEM-Screen#1]
Your work is solid and interesting. But at the methodological level, what is the difference between your proposed model and GEM (https://www.nature.com/articles/s42256-021-00438-4). Looking forward to your answers, thanks!

**Comment by jinfeng-data** [comment]
Hi, thanks for your interests on our work. Yes, we used GEM (https://www.nature.com/articles/s42256-021-00438-4), developed by Fang et al., to describe the molecules and related with the corresponding docking scores. This GEM based model, termed as GEM-Screen, can be used to enhance the virtual screening of the ultralarge libraries.

**Comment by daydayupzzl** [comment]
Thank you for your reply. Your work provides a feasible and efficient idea for artificial intelligence-assisted large-scale drug screening, which is very interesting
